/elevation_mapping:
  ros__parameters:
    enable_continuous_cleanup: false
    enable_visibility_cleanup: true
    fused_map_publishing_rate: 1.0
    init_submap_height_offset: 0.0
    initialization_method: 0
    initialize_elevation_map: false
    input_sources:
      sensors:
      - front
      # - back
      front:
        type: pointcloud
        topic: /camera/depth/color/points
        queue_size: 2
        publish_on_update: false
        sensor_processor:
          type: structured_light
          apply_voxelgrid_filter: false
          voxelgrid_filter_size: 0.0
          cutoff_min_depth: 0.2
          cutoff_max_depth: 3.25
          ignore_points_above: 2.0
          ignore_points_below: -1.0
          normal_factor_a: 0.000611
          normal_factor_b:  0.003587
          normal_factor_c: 0.3515
          normal_factor_d: 0.0
          normal_factor_e: 1.0
          lateral_factor: 0.01576
      # back:
      #   type: pointcloud
      #   topic: /camera2/depth/color/points
      #   queue_size: 2
      #   publish_on_update: false
      #   sensor_processor:
      #     type: perfect
      #     apply_voxelgrid_filter: false
      #     voxelgrid_filter_size: 0.0
      #     ignore_points_above: 10.0
      #     ignore_points_below: -5.0
    length_in_x: 5.0
    length_in_x_init_submap: 1.0
    length_in_y: 5.0
    length_in_y_init_submap: 1.0
    mahalanobis_distance_threshold: 0.5
    map_frame_id: map
    margin_init_submap: 0.3
    masked_replace_service_mask_layer_name: mask
    max_horizontal_variance: 0.5
    max_variance: 0.2
    min_horizontal_variance: 0.0
    min_update_rate: 2.0
    min_variance: 9.0e-06
    multi_height_noise: 9.0e-03
    output_topic: elevation_map_raw
    position_x: 0.0
    position_y: 0.0
    postprocessor_num_threads: 1
    postprocessor_pipeline_name: postprocessor_pipeline
    resolution: 0.2
    robot_base_frame_id: base_link
    robot_pose_cache_size: 50
    robot_pose_with_covariance_topic: /base_link_pose
    scanning_duration: 1.0
    target_frame_init_submap: footprint
    time_tolerance: 0.0
    track_point_frame_id: /robot
    track_point_x: 0.0
    track_point_y: 0.0
    track_point_z: 0.0
    underlying_map_topic: ''
    use_sim_time: false
    visibility_cleanup_rate: 1.0
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
